# https://taskfile.dev

version: '3'

vars:
  EXE_FILE: "main"

tasks:
  configure:
    sources:
      - CMakeLists.txt
    generates:
      - build/**
    cmds:
      - cmake -B build -G "Ninja"
    silent: false

  build:
    sources:
      - src/**
    generates:
      - build/{{.EXE_FILE}}.exe
    deps:
      - configure
    cmds:
      - cmake --build build
    silent: false

  default:
    deps:
      - build
    cmds:
      - build/{{.EXE_FILE}}.exe
    silent: false

  clean:
    if:
      - test -d build
    cmds:
      - rm -rf build
    silent: false
