# https://taskfile.dev

version: '3'

tasks:
  configure:
    sources:
      - CMakeLists.txt
    cmds:
      - cmake -B build -G "Ninja"
    silent: false

  build:
    sources:
      - src/**
    generates:
      - build/**
    deps:
      - configure
    cmds:
      - cmake --build build
    silent: false

  default:
    deps:
      - build
    cmds:
      - build/main.exe
    silent: false
